[package]
name = "appsdesktop"
version = "1.0.10"
description = "A Tauri App"
authors = ["you"]
edition = "2021"
default-run = "appsdesktop"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "appsdesktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset", "tray-icon"] }
tauri-plugin-opener = "2"
tauri-plugin-autostart = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["json", "stream", "multipart"] }
sqlx = { version = "0.8", features = ["sqlite", "runtime-tokio-rustls", "chrono", "uuid"] }
keyring = "3.6"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1", features = ["serde", "v4"] }
thiserror = "2"
futures = "0.3"

image = "0.25"
printpdf = "0.5"
base64 = "0.22"
sha2 = "0.11.0"
zip = { version = "8.6.0", default-features = false, features = ["deflate"] }
async-trait = "0.1.89"
tauri-plugin-global-shortcut = "2.3.2"
tauri-plugin-shell = "2.3.5"
tauri-plugin-http = "2"
tauri-plugin-fs = "2.5.1"
tokio-tungstenite = "0.26.1"
lazy_static = "1.5.0"
fastembed = "5.17.4"
cpal = "0.18.1"
hound = "3.5.1"
tauri-plugin-single-instance = "2"
regex = "1.10"
tauri-plugin-dialog = "2"
axum = { version = "0.8.9", features = ["multipart"] }
tower-http = { version = "0.7.0", features = ["cors"] }
tokio-util = { version = "0.7.19", features = ["io"] }
