import { useState } from 'react';
import { X, Copy, Check, ExternalLink, Mail, Loader2, ChevronRight, Hash } from 'lucide-react';

interface ExportPushDialogProps {
  isOpen: boolean;
  onClose: () => void;
  lectureTitle: string;
  summary: string | null;
  artifacts: Record<string, any>;
}

function buildMarkdownExport(title: string, summary: string | null, artifacts: Record<string, any>): string {
  const lines: string[] = [`# ${title}`, '', `*Generated by Bacham — ${new Date().toLocaleDateString()}*`, ''];

  if (summary) {
    lines.push('## Summary', '', summary, '');
  }

  const intel = artifacts['lecture_intelligence'];
  if (intel) {
    if (intel.action_items?.length) {
      lines.push('## Action Items', '');
      intel.action_items.forEach((item: any) => {
        const owner = item.owner ? ` *(${item.owner})*` : '';
        const due = item.due_date ? ` — Due: ${item.due_date}` : '';
        lines.push(`- [ ] ${item.task}${owner}${due}`);
      });
      lines.push('');
    }
    if (intel.key_decisions?.length) {
      lines.push('## Key Decisions', '');
      intel.key_decisions.forEach((d: any) => lines.push(`- ${d.decision || d}`));
      lines.push('');
    }
    if (intel.key_questions?.length) {
      lines.push('## Open Questions', '');
      intel.key_questions.forEach((q: any) => lines.push(`- ${q.question || q}`));
      lines.push('');
    }
  }

  return lines.join('\n');
}

function IntegrationCard({
  icon: Icon,
  title,
  description,
  action,
  actionLabel,
  isLoading,
  color = 'indigo',
}: {
  icon: any;
  title: string;
  description: string;
  action: () => void;
  actionLabel: string;
  isLoading?: boolean;
  color?: string;
}) {
  const colorMap: Record<string, string> = {
    indigo: 'from-indigo-600 to-violet-600 hover:from-indigo-500 hover:to-violet-500',
    green: 'from-emerald-600 to-teal-600 hover:from-emerald-500 hover:to-teal-500',
    purple: 'from-purple-600 to-pink-600 hover:from-purple-500 hover:to-pink-500',
    blue: 'from-blue-600 to-sky-600 hover:from-blue-500 hover:to-sky-500',
  };

  return (
    <div className="bg-surface border border-border/50 rounded-2xl p-4 flex items-center gap-4 hover:border-border/80 transition-colors group">
      <div className={`w-10 h-10 rounded-xl bg-gradient-to-br ${colorMap[color] || colorMap.indigo} flex items-center justify-center shrink-0`}>
        <Icon size={18} className="text-white" />
      </div>
      <div className="flex-1 min-w-0">
        <p className="text-sm font-semibold text-foreground">{title}</p>
        <p className="text-xs text-muted-foreground truncate">{description}</p>
      </div>
      <button
        onClick={action}
        disabled={isLoading}
        className="flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-surface-hover border border-border/50 text-xs font-medium text-foreground hover:border-border/80 hover:bg-surface transition-colors disabled:opacity-50 shrink-0 group-hover:border-primary/30 group-hover:text-primary"
      >
        {isLoading ? <Loader2 size={11} className="animate-spin" /> : <ChevronRight size={11} />}
        {actionLabel}
      </button>
    </div>
  );
}

export function ExportPushDialog({ isOpen, onClose, lectureTitle, summary, artifacts }: ExportPushDialogProps) {
  const [copied, setCopied] = useState(false);
  const [isSlackSending, setIsSlackSending] = useState(false);
  const [isNotionSending, setIsNotionSending] = useState(false);
  const [slackStatus, setSlackStatus] = useState<'idle' | 'success' | 'error'>('idle');
  const [notionStatus, setNotionStatus] = useState<'idle' | 'success' | 'error'>('idle');

  if (!isOpen) return null;

  const markdownContent = buildMarkdownExport(lectureTitle, summary, artifacts);

  const handleCopyMarkdown = () => {
    navigator.clipboard.writeText(markdownContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleEmailShare = () => {
    const subject = encodeURIComponent(`Meeting Notes: ${lectureTitle}`);
    const body = encodeURIComponent(markdownContent.substring(0, 2000));
    window.open(`mailto:?subject=${subject}&body=${body}`, '_self');
  };

  const handleSlackShare = async () => {
    const webhookUrl = localStorage.getItem('slack_webhook_url');
    if (!webhookUrl) {
      alert('Please configure your Slack webhook URL in Settings → Integrations first.');
      return;
    }
    setIsSlackSending(true);
    setSlackStatus('idle');
    try {
      const payload = {
        text: `*Meeting Notes: ${lectureTitle}*\n\n${summary?.substring(0, 400) || 'No summary available.'}${summary && summary.length > 400 ? '...' : ''}`
      };
      await fetch(webhookUrl, { method: 'POST', body: JSON.stringify(payload) });
      setSlackStatus('success');
    } catch {
      setSlackStatus('error');
    } finally {
      setIsSlackSending(false);
    }
  };

  const handleNotionShare = async () => {
    const webhookUrl = localStorage.getItem('notion_webhook_url');
    if (!webhookUrl) {
      alert('Please configure your Notion webhook URL in Settings → Integrations first.');
      return;
    }
    setIsNotionSending(true);
    setNotionStatus('idle');
    try {
      await fetch(webhookUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ title: lectureTitle, content: markdownContent }),
      });
      setNotionStatus('success');
    } catch {
      setNotionStatus('error');
    } finally {
      setIsNotionSending(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4" onClick={onClose}>
      <div className="absolute inset-0 bg-black/60 backdrop-blur-sm" />
      <div
        className="relative bg-[var(--surface)] border border-border/60 rounded-3xl shadow-2xl w-full max-w-md overflow-hidden"
        onClick={e => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between p-5 border-b border-border/40">
          <div>
            <h2 className="text-base font-semibold text-foreground">Share & Export</h2>
            <p className="text-xs text-muted-foreground mt-0.5 truncate max-w-[280px]">{lectureTitle}</p>
          </div>
          <button onClick={onClose} className="p-2 rounded-xl text-muted-foreground hover:text-foreground hover:bg-surface-hover transition-colors">
            <X size={16} />
          </button>
        </div>

        {/* Integrations */}
        <div className="p-5 space-y-3">
          <p className="text-[10px] font-semibold uppercase tracking-widest text-muted-foreground/60 mb-3">Export Options</p>

          <IntegrationCard
            icon={copied ? Check : Copy}
            title="Copy as Markdown"
            description="Copy summary, action items & decisions as Markdown"
            action={handleCopyMarkdown}
            actionLabel={copied ? 'Copied!' : 'Copy'}
            color="indigo"
          />

          <IntegrationCard
            icon={Mail}
            title="Share via Email"
            description="Open email client with notes pre-filled"
            action={handleEmailShare}
            actionLabel="Open"
            color="blue"
          />

          <IntegrationCard
            icon={Hash}
            title="Push to Slack"
            description={slackStatus === 'success' ? '✓ Sent!' : slackStatus === 'error' ? '✗ Failed — check webhook URL' : 'Post summary to your Slack channel'}
            action={handleSlackShare}
            actionLabel="Send"
            isLoading={isSlackSending}
            color="green"
          />

          <IntegrationCard
            icon={ExternalLink}
            title="Push to Notion"
            description={notionStatus === 'success' ? '✓ Sent!' : notionStatus === 'error' ? '✗ Failed — check webhook URL' : 'Create a new page in your Notion workspace'}
            action={handleNotionShare}
            actionLabel="Push"
            isLoading={isNotionSending}
            color="purple"
          />
        </div>

        {/* Footer */}
        <div className="px-5 pb-5">
          <p className="text-[10px] text-muted-foreground/50 text-center">
            Configure Slack & Notion webhook URLs in{' '}
            <span className="text-primary/70">Settings → Integrations</span>
          </p>
        </div>
      </div>
    </div>
  );
}
