import { useState, useEffect } from 'react';
import { X, Copy, Check, Mail, Loader2, ChevronRight, PlugZap, FileText } from 'lucide-react';
import { useToast } from '@/components/ui/ToastProvider';
import { pluginManager } from '@/core/integrations/PluginManager';
import { BachamPlugin } from '@/core/integrations/types';
import jsPDF from 'jspdf';

interface ExportPushDialogProps {
  isOpen: boolean;
  onClose: () => void;
  lectureTitle: string;
  summary: string | null;
  artifacts: Record<string, any>;
}

function buildMarkdownExport(title: string, summary: string | null, artifacts: Record<string, any>): string {
  const lines: string[] = [`# ${title}`, '', `*Generated by Bacham — ${new Date().toLocaleDateString()}*`, ''];

  if (summary) {
    lines.push('## Summary', '', summary, '');
  }

  const intel = artifacts['lecture_intelligence'];
  if (intel) {
    if (intel.action_items?.length) {
      lines.push('## Action Items', '');
      intel.action_items.forEach((item: any) => {
        const owner = item.owner ? ` *(${item.owner})*` : '';
        const due = item.due_date ? ` — Due: ${item.due_date}` : '';
        lines.push(`- [ ] ${item.task}${owner}${due}`);
      });
      lines.push('');
    }
    if (intel.key_decisions?.length) {
      lines.push('## Key Decisions', '');
      intel.key_decisions.forEach((d: any) => lines.push(`- ${d.decision || d}`));
      lines.push('');
    }
    if (intel.key_questions?.length) {
      lines.push('## Open Questions', '');
      intel.key_questions.forEach((q: any) => lines.push(`- ${q.question || q}`));
      lines.push('');
    }
  }

  return lines.join('\n');
}

function IntegrationCard({
  icon: Icon,
  title,
  description,
  action,
  actionLabel,
  isLoading,
  color = 'indigo',
}: {
  icon: any;
  title: string;
  description: string;
  action: () => void;
  actionLabel: string;
  isLoading?: boolean;
  color?: string;
}) {
  const colorMap: Record<string, string> = {
    indigo: 'from-indigo-600 to-violet-600 hover:from-indigo-500 hover:to-violet-500',
    green: 'from-emerald-600 to-teal-600 hover:from-emerald-500 hover:to-teal-500',
    purple: 'from-purple-600 to-pink-600 hover:from-purple-500 hover:to-pink-500',
    blue: 'from-blue-600 to-sky-600 hover:from-blue-500 hover:to-sky-500',
  };

  return (
    <div className="bg-surface border border-border/50 rounded-2xl p-4 flex items-center gap-4 hover:border-border/80 transition-colors group">
      <div className={`w-10 h-10 rounded-xl bg-gradient-to-br ${colorMap[color] || colorMap.indigo} flex items-center justify-center shrink-0`}>
        <Icon size={18} className="text-white" />
      </div>
      <div className="flex-1 min-w-0">
        <p className="text-sm font-semibold text-foreground">{title}</p>
        <p className="text-xs text-muted-foreground truncate">{description}</p>
      </div>
      <button
        onClick={action}
        disabled={isLoading}
        className="flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-surface-hover border border-border/50 text-xs font-medium text-foreground hover:border-border/80 hover:bg-surface transition-colors disabled:opacity-50 shrink-0 group-hover:border-primary/30 group-hover:text-primary"
      >
        {isLoading ? <Loader2 size={11} className="animate-spin" /> : <ChevronRight size={11} />}
        {actionLabel}
      </button>
    </div>
  );
}

export function ExportPushDialog({ isOpen, onClose, lectureTitle, summary, artifacts }: ExportPushDialogProps) {
  const [copied, setCopied] = useState(false);
  const [exportPlugins, setExportPlugins] = useState<BachamPlugin[]>([]);
  const [pluginStatuses, setPluginStatuses] = useState<Record<string, 'idle' | 'loading' | 'success' | 'error'>>({});
  const { showToast } = useToast();

  useEffect(() => {
    if (isOpen) {
      const loadPlugins = async () => {
        const allPlugins = pluginManager.getPlugins().filter(p => p.actions?.export);
        const connectedPlugins = [];
        for (const p of allPlugins) {
          const connected = p.auth?.type === 'none' ? true : await p.auth?.isConnected?.();
          if (connected) {
            connectedPlugins.push(p);
          }
        }
        setExportPlugins(connectedPlugins);
      };
      loadPlugins();
    }
  }, [isOpen]);

  if (!isOpen) return null;

  const markdownContent = buildMarkdownExport(lectureTitle, summary, artifacts);

  const handleCopyMarkdown = () => {
    navigator.clipboard.writeText(markdownContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleEmailShare = () => {
    const subject = encodeURIComponent(`Meeting Notes: ${lectureTitle}`);
    const body = encodeURIComponent(markdownContent.substring(0, 2000));
    window.open(`mailto:?subject=${subject}&body=${body}`, '_self');
  };

  const handlePluginExport = async (plugin: BachamPlugin) => {
    if (!plugin.actions?.export) return;
    
    setPluginStatuses(prev => ({ ...prev, [plugin.manifest.id]: 'loading' }));
    try {
      const data = { title: lectureTitle, summary, content: markdownContent };
      await plugin.actions.export(data);
      setPluginStatuses(prev => ({ ...prev, [plugin.manifest.id]: 'success' }));
      setTimeout(() => setPluginStatuses(prev => ({ ...prev, [plugin.manifest.id]: 'idle' })), 3000);
    } catch (e: any) {
      console.error('[Export Error]', e);
      showToast(`Export Failed: ${e.message}`, 'error');
      setPluginStatuses(prev => ({ ...prev, [plugin.manifest.id]: 'error' }));
      setTimeout(() => setPluginStatuses(prev => ({ ...prev, [plugin.manifest.id]: 'idle' })), 4000);
    }
  };

  const handleExportMarkdownFile = () => {
    try {
      const safeTitle = lectureTitle.replace(/[^a-z0-9]/gi, '_').toLowerCase();
      const blob = new Blob([markdownContent], { type: 'text/markdown' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${safeTitle}.md`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      
      showToast('Exported Markdown file successfully!', 'success');
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (error) {
      console.error(error);
      showToast('Failed to export markdown file.', 'error');
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4" onClick={onClose}>
      <div className="absolute inset-0 bg-black/60 backdrop-blur-sm" />
      <div
        className="relative bg-[var(--surface)] border border-border/80 rounded-3xl shadow-lg w-full max-w-md max-h-[85vh] flex flex-col overflow-hidden"
        onClick={e => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between p-5 border-b border-border/40 shrink-0">
          <div>
            <h2 className="text-base font-semibold text-foreground">Share & Export</h2>
            <p className="text-xs text-muted-foreground mt-0.5 truncate max-w-[280px]">{lectureTitle}</p>
          </div>
          <button onClick={onClose} className="p-2 rounded-xl text-muted-foreground hover:text-foreground hover:bg-surface-hover transition-colors">
            <X size={16} />
          </button>
        </div>

        {/* Integrations */}
        <div className="p-5 space-y-3 overflow-y-auto">
          <p className="text-[10px] font-semibold uppercase tracking-widest text-muted-foreground/60 mb-3">Basic Options</p>

          <IntegrationCard
            icon={copied ? Check : Copy}
            title="Copy as Markdown"
            description="Copy summary, action items & decisions as Markdown"
            action={handleCopyMarkdown}
            actionLabel={copied ? 'Copied!' : 'Copy'}
            color="indigo"
          />

          <IntegrationCard
            icon={FileText}
            title="Export Markdown File"
            description="Save as a local .md file for Obsidian or Notion"
            action={handleExportMarkdownFile}
            actionLabel="Save"
            color="green"
          />

          <IntegrationCard
            icon={Mail}
            title="Share via Email"
            description="Open email client with notes pre-filled"
            action={handleEmailShare}
            actionLabel="Open"
            color="blue"
          />
          
          <IntegrationCard
            icon={FileText}
            title="Export as PDF"
            description="Download notes as a PDF document"
            action={() => {
              const doc = new jsPDF();
              // Add a nice header
              doc.setFontSize(18);
              doc.text(lectureTitle, 15, 20);
              doc.setFontSize(10);
              doc.setTextColor(100, 100, 100);
              doc.text(`Generated by Bacham — ${new Date().toLocaleDateString()}`, 15, 28);
              doc.setTextColor(0, 0, 0);
              
              // Add content
              doc.setFontSize(12);
              const contentLines = markdownContent.split('\n').filter(line => !line.startsWith('# '));
              const splitText = doc.splitTextToSize(contentLines.join('\n'), 180);
              doc.text(splitText, 15, 40);
              doc.save(`${lectureTitle}.pdf`);
            }}
            actionLabel="Save"
            color="green"
          />

          <p className="text-[10px] font-semibold uppercase tracking-widest text-muted-foreground/60 mt-6 mb-3">Your Connected Plugins</p>
          
          {exportPlugins.length === 0 ? (
            <div className="bg-surface/50 border border-border/40 rounded-2xl p-6 text-center">
               <PlugZap size={24} className="mx-auto text-muted-foreground/50 mb-3" />
               <h3 className="text-sm font-medium text-foreground">No plugins connected</h3>
               <p className="text-xs text-muted-foreground mt-1">Go to Settings &rarr; Integrations to connect Notion, Slack, and more.</p>
            </div>
          ) : (
            exportPlugins.map(plugin => {
              const status = pluginStatuses[plugin.manifest.id] || 'idle';
              const isSending = status === 'loading';
              let desc = plugin.manifest.description;
              if (status === 'success') desc = '✓ Export successful!';
              if (status === 'error') desc = '✗ Export failed. Check connection.';

              return (
                <IntegrationCard
                  key={plugin.manifest.id}
                  icon={PlugZap}
                  title={`Send to ${plugin.manifest.name}`}
                  description={desc}
                  action={() => handlePluginExport(plugin)}
                  actionLabel={isSending ? 'Sending' : 'Send'}
                  isLoading={isSending}
                  color="purple"
                />
              );
            })
          )}
        </div>
      </div>
    </div>
  );
}
