import { useState, useEffect, useMemo } from 'react';
import { createPortal } from 'react-dom';
import { X, Copy, Check, Mail, Loader2, FileText, Eye, Download, ChevronLeft, Sparkles } from 'lucide-react';
import { useToast } from '@/components/ui/ToastProvider';
import jsPDF from 'jspdf';
import { TauriClient } from '@/infrastructure/tauri-client';
import { save } from '@tauri-apps/plugin-dialog';
import { writeTextFile } from '@tauri-apps/plugin-fs';

interface ExportPushDialogProps {
  isOpen: boolean;
  onClose: () => void;
  lectureId: string;
  lectureTitle: string;
  summary: string | null;
  artifacts: Record<string, any>;
  transcript?: string | null;
}

function buildMarkdownExport(title: string, summary: string | null, artifacts: Record<string, any>, transcript?: string | null): string {
  const lines: string[] = [`# ${title}`, '', `*Generated by Bacham — ${new Date().toLocaleDateString()}*`, ''];

  if (summary) {
    lines.push('## Summary', '', summary, '');
  }

  const intel = artifacts['lecture_intelligence'];
  if (intel) {
    if (intel.action_items?.length) {
      lines.push('## Action Items', '');
      intel.action_items.forEach((item: any) => {
        const owner = item.owner ? ` *(${item.owner})*` : '';
        const due = item.due_date ? ` — Due: ${item.due_date}` : '';
        lines.push(`- [ ] ${item.task}${owner}${due}`);
      });
      lines.push('');
    }
    if (intel.key_decisions?.length) {
      lines.push('## Key Decisions', '');
      intel.key_decisions.forEach((d: any) => lines.push(`- ${d.decision || d}`));
      lines.push('');
    }
    if (intel.key_questions?.length) {
      lines.push('## Open Questions', '');
      intel.key_questions.forEach((q: any) => lines.push(`- ${q.question || q}`));
      lines.push('');
    }
  }

  if (transcript) {
    lines.push('## Transcript', '', transcript, '');
  }

  return lines.join('\n');
}

function applyInline(text: string): string {
  return text
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.+?)\*/g, '<em style="color:var(--muted-foreground)">$1</em>')
    .replace(/`(.+?)`/g, '<code style="background:var(--surface-hover);padding:1px 5px;border-radius:4px;font-size:0.8em">$1</code>');
}

function markdownToHtml(md: string): string {
  const lines = md.split('\n');
  let html = '';
  let inList = false;

  for (const raw of lines) {
    const line = raw;
    if (/^# /.test(line)) {
      if (inList) { html += '</ul>'; inList = false; }
      html += `<h1 style="font-size:1.35rem;font-weight:700;margin:0 0 4px;color:var(--foreground)">${applyInline(line.slice(2))}</h1>`;
    } else if (/^## /.test(line)) {
      if (inList) { html += '</ul>'; inList = false; }
      html += `<h2 style="font-size:1rem;font-weight:600;margin:20px 0 6px;color:var(--foreground);border-bottom:1px solid var(--border);padding-bottom:4px">${applyInline(line.slice(3))}</h2>`;
    } else if (/^---+$/.test(line)) {
      if (inList) { html += '</ul>'; inList = false; }
      html += `<hr style="border:none;border-top:1px solid var(--border);margin:12px 0"/>`;
    } else if (/^- \[ \] /.test(line)) {
      if (!inList) { html += '<ul style="list-style:none;padding:0;margin:0">'; inList = true; }
      html += `<li style="display:flex;align-items:flex-start;gap:8px;margin:5px 0;font-size:0.85rem;color:var(--foreground)"><input type="checkbox" style="margin-top:2px;accent-color:var(--primary)" disabled/><span>${applyInline(line.slice(6))}</span></li>`;
    } else if (/^- /.test(line)) {
      if (!inList) { html += '<ul style="list-style:disc;padding-left:18px;margin:0">'; inList = true; }
      html += `<li style="margin:4px 0;font-size:0.85rem;color:var(--foreground)">${applyInline(line.slice(2))}</li>`;
    } else {
      if (inList) { html += '</ul>'; inList = false; }
      if (line.trim() === '') {
        html += `<div style="height:6px"></div>`;
      } else {
        html += `<p style="margin:3px 0;font-size:0.85rem;color:var(--foreground)">${applyInline(line)}</p>`;
      }
    }
  }
  if (inList) html += '</ul>';
  return html;
}

type PreviewFormat = 'markdown' | 'pdf' | 'html' | 'json' | 'magic_link';
type DialogView = 'options' | 'preview';

function IntegrationCard({
  icon: Icon,
  title,
  description,
  action,
  actionLabel,
  isLoading,
  color = 'indigo',
  onPreview,
}: {
  icon: any;
  title: string;
  description: string;
  action: () => void;
  actionLabel: string;
  isLoading?: boolean;
  color?: string;
  onPreview?: () => void;
}) {
  const colorMap: Record<string, string> = {
    indigo: 'from-indigo-600 to-violet-600',
    green: 'from-emerald-600 to-teal-600',
    purple: 'from-purple-600 to-pink-600',
    blue: 'from-blue-600 to-sky-600',
  };

  return (
    <div className="bg-surface border border-border/50 rounded-2xl p-4 flex items-center gap-4 hover:border-border/80 transition-colors group">
      <div className={`w-10 h-10 rounded-xl bg-gradient-to-br ${colorMap[color] || colorMap.indigo} flex items-center justify-center shrink-0`}>
        <Icon size={18} className="text-white" />
      </div>
      <div className="flex-1 min-w-0">
        <p className="text-sm font-semibold text-foreground">{title}</p>
        <p className="text-xs text-muted-foreground truncate">{description}</p>
      </div>
      <div className="flex items-center gap-1.5 shrink-0">
        {onPreview && (
          <button
            onClick={onPreview}
            title="Preview before exporting"
            className="flex items-center gap-1 px-2.5 py-1.5 rounded-full bg-surface-hover border border-border/50 text-xs font-medium text-muted-foreground hover:text-foreground hover:border-border/80 transition-colors"
          >
            <Eye size={11} />
            Preview
          </button>
        )}
        <button
          onClick={action}
          disabled={isLoading}
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-surface-hover border border-border/50 text-xs font-medium text-foreground hover:border-border/80 hover:bg-surface transition-colors disabled:opacity-50 group-hover:border-primary/30 group-hover:text-primary"
        >
          {isLoading ? <Loader2 size={11} className="animate-spin" /> : <Download size={11} />}
          {actionLabel}
        </button>
      </div>
    </div>
  );
}

function PreviewPanel({
  format,
  content,
  onBack,
  onExport,
  isLoading
}: {
  format: PreviewFormat;
  content: string;
  onBack: () => void;
  onExport: () => void;
  isLoading?: boolean;
}) {
  const formatLabel: Record<PreviewFormat, string> = {
    markdown: 'Markdown (.md)',
    pdf: 'PDF Document',
    html: 'HTML Page',
    json: 'JSON Data',
    magic_link: 'Interactive Magic Link',
  };

  const previewHtml = useMemo(() => format !== 'magic_link' ? markdownToHtml(content) : '', [content, format]);

  return (
    <div className="flex flex-col h-full">
      <div className="flex items-center justify-between px-5 py-3 border-b border-border/40 shrink-0">
        <div className="flex items-center gap-2">
          <button
            onClick={onBack}
            className="p-1.5 rounded-lg text-muted-foreground hover:text-foreground hover:bg-surface-hover transition-colors"
          >
            <ChevronLeft size={15} />
          </button>
          <span className="text-sm font-semibold text-foreground">Preview</span>
          <span className="text-xs text-muted-foreground bg-surface-hover px-2 py-0.5 rounded-full border border-border/40">
            {formatLabel[format]}
          </span>
        </div>
        <button
          onClick={onExport}
          disabled={isLoading}
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-gradient-to-r from-indigo-600 to-violet-600 hover:from-indigo-500 hover:to-violet-500 text-white text-xs font-semibold transition-all shadow-sm disabled:opacity-50"
        >
          {isLoading ? <Loader2 size={11} className="animate-spin" /> : <Download size={11} />}
          Export Now
        </button>
      </div>

      <div className="flex-1 overflow-hidden flex flex-col relative">
        {isLoading && (
          <div className="absolute inset-0 z-10 bg-surface/50 backdrop-blur-sm flex items-center justify-center">
            <Loader2 className="animate-spin text-primary w-8 h-8" />
          </div>
        )}
        
        {(format === 'markdown' || format === 'pdf') && (
          <>
            <div className="flex border-b border-border/40 bg-surface shrink-0">
              <span className="px-4 py-2 text-xs font-medium text-primary border-b-2 border-primary">
                {format === 'pdf' ? 'PDF Preview' : 'Rendered Preview'}
              </span>
            </div>
            {format === 'pdf' ? (
              <div className="flex-1 overflow-y-auto bg-zinc-100 dark:bg-zinc-900 p-4 flex justify-center">
                <div
                  className="bg-white dark:bg-zinc-800 shadow-xl rounded-sm w-full max-w-md p-8"
                  style={{ fontFamily: 'Georgia, serif', color: '#1a1a1a', minHeight: 500 }}
                >
                  <div dangerouslySetInnerHTML={{ __html: previewHtml }} />
                  <p className="text-[10px] text-zinc-400 mt-8 pt-4 border-t border-zinc-200">
                    Generated by Bacham — {new Date().toLocaleDateString()}
                  </p>
                </div>
              </div>
            ) : (
              <div
                className="flex-1 overflow-y-auto p-5"
                dangerouslySetInnerHTML={{ __html: previewHtml }}
              />
            )}
          </>
        )}

        {(format === 'html' || format === 'json') && (
          <>
            <div className="flex border-b border-border/40 bg-surface shrink-0">
              <span className="px-4 py-2 text-xs font-medium text-primary border-b-2 border-primary">
                {format === 'html' ? 'HTML Source' : 'JSON Structure'}
              </span>
            </div>
            <div className="flex-1 overflow-y-auto p-4">
              <pre className="text-[11px] font-mono text-foreground/80 whitespace-pre-wrap break-all leading-relaxed bg-surface-hover border border-border/40 rounded-xl p-4">
                {content}
              </pre>
            </div>
          </>
        )}

        {format === 'magic_link' && content && !isLoading && (
          <>
            <div className="flex border-b border-border/40 bg-surface shrink-0">
              <span className="px-4 py-2 text-xs font-medium text-primary border-b-2 border-primary">
                Magic Link Render
              </span>
            </div>
            <div className="flex-1 bg-[#09090b] p-4 relative overflow-hidden">
               <iframe
                 srcDoc={content}
                 className="w-full h-full bg-[#09090b] rounded-xl shadow-2xl border border-white/10"
                 sandbox="allow-scripts"
               />
            </div>
          </>
        )}
      </div>
    </div>
  );
}

export function ExportPushDialog({ isOpen, onClose, lectureId, lectureTitle, summary, artifacts, transcript }: ExportPushDialogProps) {
  const [copied, setCopied] = useState(false);
  const [view, setView] = useState<DialogView>('options');
  const [previewFormat, setPreviewFormat] = useState<PreviewFormat>('markdown');
  const [magicLinkCache, setMagicLinkCache] = useState<string>('');
  const [isLoadingPreview, setIsLoadingPreview] = useState(false);
  const { showToast } = useToast();

  useEffect(() => {
    if (isOpen) {
      setView('options');
    }
  }, [isOpen]);

  if (!isOpen) return null;

  const markdownContent = buildMarkdownExport(lectureTitle, summary, artifacts, transcript);

  const htmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${lectureTitle}</title>
  <style>body{font-family:sans-serif;max-width:800px;margin:40px auto;padding:0 20px;line-height:1.6;color:#1a1a1a}h1{font-size:1.8rem;margin-bottom:4px}h2{font-size:1.1rem;border-bottom:1px solid #eee;padding-bottom:6px;margin-top:24px}ul{padding-left:20px}li{margin:4px 0}.meta{color:#888;font-size:.85rem}</style>
</head>
<body>
${markdownToHtml(markdownContent)}
</body>
</html>`;

  const jsonContent = JSON.stringify({
    title: lectureTitle,
    exportedAt: new Date().toISOString(),
    summary,
    actionItems: artifacts['lecture_intelligence']?.action_items ?? [],
    keyDecisions: artifacts['lecture_intelligence']?.key_decisions ?? [],
    openQuestions: artifacts['lecture_intelligence']?.key_questions ?? [],
    transcript: transcript || '',
  }, null, 2);

  const previewContent: Record<PreviewFormat, string> = {
    markdown: markdownContent,
    pdf: markdownContent,
    html: htmlContent,
    json: jsonContent,
    magic_link: magicLinkCache,
  };

  async function openPreview(fmt: PreviewFormat) {
    if (fmt === 'magic_link' && !magicLinkCache) {
      setIsLoadingPreview(true);
      setView('preview');
      setPreviewFormat(fmt);
      try {
        const html = await TauriClient.generateMagicLinkHtml(lectureId);
        setMagicLinkCache(html);
      } catch (e) {
        console.error(e);
        showToast('Failed to generate Magic Link preview', 'error');
        setView('options');
      } finally {
        setIsLoadingPreview(false);
      }
      return;
    }
    setPreviewFormat(fmt);
    setView('preview');
  }

  const handleCopyMarkdown = () => {
    navigator.clipboard.writeText(markdownContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleEmailShare = () => {
    const subject = encodeURIComponent(`Meeting Notes: ${lectureTitle}`);
    const body = encodeURIComponent(markdownContent.substring(0, 2000));
    window.open(`mailto:?subject=${subject}&body=${body}`, '_self');
  };

  const handleExportMarkdownFile = async () => {
    try {
      const safeTitle = lectureTitle.replace(/[^a-z0-9]/gi, '_').toLowerCase();
      try {
        const filePath = await save({
          title: 'Export Markdown',
          defaultPath: `${safeTitle}.md`,
          filters: [{ name: 'Markdown', extensions: ['md'] }],
        });
        if (filePath) {
          await writeTextFile(filePath, markdownContent);
          showToast('Exported Markdown file successfully!', 'success', {
            label: 'Open File', onClick: () => import('@tauri-apps/plugin-shell').then(({ open }) => open(filePath).catch(console.error))
          });
        }
      } catch (e) {
        // Fallback for non-tauri or error
        const a = Object.assign(document.createElement('a'), {
          href: URL.createObjectURL(new Blob([markdownContent], { type: 'text/markdown' })),
          download: `${safeTitle}.md`,
        });
        document.body.appendChild(a); a.click(); document.body.removeChild(a);
        showToast('Exported Markdown file successfully!', 'success');
      }
    } catch (error) {
      console.error(error);
      showToast('Failed to export markdown file.', 'error');
    }
  };

  const handleExportPdf = () => {
    const doc = new jsPDF();
    doc.setFontSize(18); doc.text(lectureTitle, 15, 20);
    doc.setFontSize(10); doc.setTextColor(100, 100, 100);
    doc.text(`Generated by Bacham — ${new Date().toLocaleDateString()}`, 15, 28);
    doc.setTextColor(0, 0, 0); doc.setFontSize(12);
    const contentLines = markdownContent.split('\n').filter(l => !l.startsWith('# '));
    doc.text(doc.splitTextToSize(contentLines.join('\n'), 180), 15, 40);
    doc.save(`${lectureTitle}.pdf`);
    showToast('PDF exported successfully!', 'success');
  };

  const handleExportHtml = async () => {
    try {
      const safeTitle = lectureTitle.replace(/[^a-z0-9]/gi, '_').toLowerCase();
      try {
        const fp = await save({ title: 'Export HTML', defaultPath: `${safeTitle}.html`, filters: [{ name: 'HTML', extensions: ['html'] }] });
        if (fp) { await writeTextFile(fp, htmlContent); showToast('HTML exported!', 'success'); }
      } catch (e) {
        const a = Object.assign(document.createElement('a'), { href: URL.createObjectURL(new Blob([htmlContent], { type: 'text/html' })), download: `${safeTitle}.html` });
        document.body.appendChild(a); a.click(); document.body.removeChild(a);
        showToast('HTML exported!', 'success');
      }
    } catch { showToast('Failed to export HTML.', 'error'); }
  };

  const handleExportJson = async () => {
    try {
      const safeTitle = lectureTitle.replace(/[^a-z0-9]/gi, '_').toLowerCase();
      try {
        const fp = await save({ title: 'Export JSON', defaultPath: `${safeTitle}.json`, filters: [{ name: 'JSON', extensions: ['json'] }] });
        if (fp) { await writeTextFile(fp, jsonContent); showToast('JSON exported!', 'success'); }
      } catch (e) {
        const a = Object.assign(document.createElement('a'), { href: URL.createObjectURL(new Blob([jsonContent], { type: 'application/json' })), download: `${safeTitle}.json` });
        document.body.appendChild(a); a.click(); document.body.removeChild(a);
        showToast('JSON exported!', 'success');
      }
    } catch { showToast('Failed to export JSON.', 'error'); }
  };

  const handleExportMagicLink = async () => {
    try {
      const safeTitle = lectureTitle.replace(/[^a-z0-9]/gi, '_').toLowerCase();
      
      let html = magicLinkCache;
      if (!html) {
         html = await TauriClient.generateMagicLinkHtml(lectureId);
      }

      try {
        const fp = await save({ title: 'Export Magic Link', defaultPath: `magic_link_${safeTitle}.html`, filters: [{ name: 'HTML', extensions: ['html'] }] });
        if (fp) { 
           await writeTextFile(fp, html); 
           showToast('Magic Link exported successfully!', 'success', {
             label: 'Open', onClick: () => import('@tauri-apps/plugin-shell').then(({ open }) => open(fp).catch(console.error))
           }); 
        }
      } catch (e) {
        const a = Object.assign(document.createElement('a'), { href: URL.createObjectURL(new Blob([html], { type: 'text/html' })), download: `magic_link_${safeTitle}.html` });
        document.body.appendChild(a); a.click(); document.body.removeChild(a);
        showToast('Magic Link exported successfully!', 'success');
      }
    } catch (e) {
      console.error(e);
      showToast('Failed to export Magic Link.', 'error');
    }
  };

  const exportHandlers: Record<PreviewFormat, () => void> = {
    markdown: handleExportMarkdownFile,
    pdf: handleExportPdf,
    html: handleExportHtml,
    json: handleExportJson,
    magic_link: handleExportMagicLink,
  };

  if (!isOpen) return null;

  return createPortal(
    <div className="fixed inset-0 z-[9999] flex items-center justify-center p-4 bg-black/40 dark:bg-black/70 backdrop-blur-md animate-in fade-in duration-200" onClick={onClose}>
      <div
        className="relative bg-[var(--surface)] border border-border/60 rounded-3xl shadow-2xl w-full max-w-md flex flex-col overflow-hidden"
        style={{ height: view === 'preview' ? '80vh' : 'auto', maxHeight: '85vh' }}
        onClick={e => e.stopPropagation()}
      >
        {view === 'preview' ? (
          <PreviewPanel
            format={previewFormat}
            content={previewContent[previewFormat]}
            onBack={() => setView('options')}
            onExport={exportHandlers[previewFormat]}
            isLoading={isLoadingPreview}
          />
        ) : (
          <>
            {/* Header */}
            <div className="flex items-center justify-between p-5 border-b border-border/40 shrink-0">
              <div>
                <h2 className="text-base font-semibold text-foreground">Share & Export</h2>
                <p className="text-xs text-muted-foreground mt-0.5 truncate max-w-[280px]">{lectureTitle}</p>
              </div>
              <button onClick={onClose} className="p-2 rounded-xl text-muted-foreground hover:text-foreground hover:bg-surface-hover transition-colors">
                <X size={16} />
              </button>
            </div>

            {/* Options list */}
            <div className="p-5 space-y-3 overflow-y-auto">
              <p className="text-[10px] font-semibold uppercase tracking-widest text-muted-foreground/60 mb-3">Premium Export</p>

              <IntegrationCard
                icon={Sparkles}
                title="BACHAM Magic Link"
                description="Interactive offline webpage with notes & transcript"
                action={handleExportMagicLink}
                actionLabel="Save"
                color="purple"
                onPreview={() => openPreview('magic_link')}
              />

              <p className="text-[10px] font-semibold uppercase tracking-widest text-muted-foreground/60 mt-6 mb-3">Basic Options</p>

              <IntegrationCard
                icon={copied ? Check : Copy}
                title="Copy as Markdown"
                description="Copy summary, action items & decisions as Markdown"
                action={handleCopyMarkdown}
                actionLabel={copied ? 'Copied!' : 'Copy'}
                color="indigo"
              />

              <IntegrationCard
                icon={FileText}
                title="Export Markdown File"
                description="Save as a local .md file for Obsidian or Notion"
                action={handleExportMarkdownFile}
                actionLabel="Save"
                color="green"
                onPreview={() => openPreview('markdown')}
              />

              <IntegrationCard
                icon={Mail}
                title="Share via Email"
                description="Open email client with notes pre-filled"
                action={handleEmailShare}
                actionLabel="Open"
                color="blue"
              />

              <IntegrationCard
                icon={FileText}
                title="Export as PDF"
                description="Download notes as a formatted PDF document"
                action={handleExportPdf}
                actionLabel="Save"
                color="green"
                onPreview={() => openPreview('pdf')}
              />

              <IntegrationCard
                icon={FileText}
                title="Export as HTML"
                description="Basic webpage with just your notes"
                action={handleExportHtml}
                actionLabel="Save"
                color="blue"
                onPreview={() => openPreview('html')}
              />

              <IntegrationCard
                icon={FileText}
                title="Export as JSON"
                description="Structured data for custom workflows and APIs"
                action={handleExportJson}
                actionLabel="Save"
                color="indigo"
                onPreview={() => openPreview('json')}
              />
            </div>
          </>
        )}
      </div>
    </div>,
    document.body
  );
}
